#!/bin/bash
#Scripting file for running multiple training instances. If there are more CUDA cores on your machine the device IDs can be changed.
#General usage: CUDA_VISIBLE_DEVICES=<CUDA DEVICE ID> timeout <hours>h python AutomatedFODExperimentalDataExperiments_train_segm.py <NumberOfObjects> <Run>
CUDA_VISIBLE_DEVICES=0 timeout 9h python AutomatedFODExperimentalDataExperimentsMSD_train_segm.py 1 0
CUDA_VISIBLE_DEVICES=0 timeout 9h python AutomatedFODExperimentalDataExperimentsMSD_train_segm.py 2 0
CUDA_VISIBLE_DEVICES=0 timeout 9h python AutomatedFODExperimentalDataExperimentsMSD_train_segm.py 1 1
CUDA_VISIBLE_DEVICES=0 timeout 9h python AutomatedFODExperimentalDataExperimentsMSD_train_segm.py 2 1
CUDA_VISIBLE_DEVICES=0 timeout 9h python AutomatedFODExperimentalDataExperimentsMSD_train_segm.py 1 2
CUDA_VISIBLE_DEVICES=0 timeout 9h python AutomatedFODExperimentalDataExperimentsMSD_train_segm.py 2 2
CUDA_VISIBLE_DEVICES=0 timeout 9h python AutomatedFODExperimentalDataExperimentsMSD_train_segm.py 1 3
CUDA_VISIBLE_DEVICES=0 timeout 9h python AutomatedFODExperimentalDataExperimentsMSD_train_segm.py 2 3
CUDA_VISIBLE_DEVICES=0 timeout 9h python AutomatedFODExperimentalDataExperimentsMSD_train_segm.py 1 4
CUDA_VISIBLE_DEVICES=0 timeout 9h python AutomatedFODExperimentalDataExperimentsMSD_train_segm.py 2 4
